var filmInfo = {
        "ID": "3",
        "shortCode": "",
        "title": "Короли Лев",
        "rating": "0+",
        "ratingDescription": "",
        "synopsis": "Одинадцятирічна дівчинка Поліна ніколи не бачила своїх батьків. Вона нічого не знає про своє минуле та повинна жити не з найкращого тітонькою та двоюрідним братом. Це єдині рідні люди, які у неї є. Тільки ось вони багато приховують від дівчинки – наприклад, те, що в неї є магічні здібності. Або те, що вони хочуть від Поліни незабаром позбутися, щоб отримати чарівну кіностудію \"Сінема\". Чим же вона така особлива? А тим, що через неї можна потрапити до зовсім іншого світу – чарівного світу кіно, де живуть усі персонажі. Саме туди незабаром і потрапить Поліна, там вона зможе дізнатися історію її батьків. Потрібно вірити в диво, адже воно навколо нас.",
        "shortSynopsis": "",
        "HOFilmCode": "F000000292",
        "CorporateFilmId": "",
        "runTime": 95,
        "openingDate": "2019-08-22T00:00:00",
        "graphicUrl": "",
        "filmNameUrl": "2019",
        "trailerUrl": "https://youtu.be/TunAEgogHNk",
        "additionalUrls": [],
        "isComingSoon": true,
        "isScheduledAtCinema": false,
        "titleAlt": "Поліна і таємниця кіностудії",
        "ratingAlt": "0",
        "ratingDescriptionAlt": "",
        "synopsisAlt": "Україна, Франція, Бельгія",
        "shortSynopsisAlt": "Wild Tribe Films, Kinorob",
        "websiteUrl": "",
        "genreId": "0000000001",
        "eDICode": null,
        "twitterTag": "українська",
        "titleTranslations": [],
        "synopsisTranslations": [],
        "shortSynopsisTranslations": [],
        "ratingDescriptionTranslations": [],
        "customerRatingStatistics": {
         "ratingCount": 0,
         "averageScore": null
        },
        "customerRatingTrailerStatistics": {
         "ratingCount": 1,
         "ratingCountLiked": 0
        },
        "filmWebId": ""
       }
    
       var filmInfo1 = {
        "ID": "1",
        "shortCode": "",
        "title": "Гарри Поттер",
        "rating": "0+",
        "ratingDescription": "",
        "synopsis": "Одинадцятирічна дівчинка Поліна ніколи не бачила своїх батьків. Вона нічого не знає про своє минуле та повинна жити не з найкращого тітонькою та двоюрідним братом. Це єдині рідні люди, які у неї є. Тільки ось вони багато приховують від дівчинки – наприклад, те, що в неї є магічні здібності. Або те, що вони хочуть від Поліни незабаром позбутися, щоб отримати чарівну кіностудію \"Сінема\". Чим же вона така особлива? А тим, що через неї можна потрапити до зовсім іншого світу – чарівного світу кіно, де живуть усі персонажі. Саме туди незабаром і потрапить Поліна, там вона зможе дізнатися історію її батьків. Потрібно вірити в диво, адже воно навколо нас.",
        "shortSynopsis": "",
        "HOFilmCode": "F000000292",
        "CorporateFilmId": "",
        "runTime": 95,
        "openingDate": "2019-08-22T00:00:00",
        "graphicUrl": "",
        "filmNameUrl": "2019",
        "trailerUrl": "https://youtu.be/TunAEgogHNk",
        "additionalUrls": [],
        "isComingSoon": true,
        "isScheduledAtCinema": false,
        "titleAlt": "Поліна і таємниця кіностудії",
        "ratingAlt": "1",
        "ratingDescriptionAlt": "",
        "synopsisAlt": "Україна, Франція, Бельгія",
        "shortSynopsisAlt": "Wild Tribe Films, Kinorob",
        "websiteUrl": "",
        "genreId": "0000000002",
        "eDICode": null,
        "twitterTag": "українська",
        "titleTranslations": [],
        "synopsisTranslations": [],
        "shortSynopsisTranslations": [],
        "ratingDescriptionTranslations": [],
        "customerRatingStatistics": {
         "ratingCount": 0,
         "averageScore": null
        },
        "customerRatingTrailerStatistics": {
         "ratingCount": 2,
         "ratingCountLiked": 0
        },
        "filmWebId": ""
       }
    
       var filmInfo2 = {
        "ID": "2",
        "shortCode": "",
        "title": "ПОЛІНА І ТАЄМНИЦЯ КІНОСТУДІЇ",
        "rating": "0+",
        "ratingDescription": "",
        "synopsis": "Одинадцятирічна дівчинка Поліна ніколи не бачила своїх батьків. Вона нічого не знає про своє минуле та повинна жити не з найкращого тітонькою та двоюрідним братом. Це єдині рідні люди, які у неї є. Тільки ось вони багато приховують від дівчинки – наприклад, те, що в неї є магічні здібності. Або те, що вони хочуть від Поліни незабаром позбутися, щоб отримати чарівну кіностудію \"Сінема\". Чим же вона така особлива? А тим, що через неї можна потрапити до зовсім іншого світу – чарівного світу кіно, де живуть усі персонажі. Саме туди незабаром і потрапить Поліна, там вона зможе дізнатися історію її батьків. Потрібно вірити в диво, адже воно навколо нас.",
        "shortSynopsis": "",
        "HOFilmCode": "F000000292",
        "CorporateFilmId": "",
        "runTime": 95,
        "openingDate": "2019-08-22T00:00:00",
        "graphicUrl": "",
        "filmNameUrl": "2019",
        "trailerUrl": "https://youtu.be/TunAEgogHNk",
        "additionalUrls": [],
        "isComingSoon": true,
        "isScheduledAtCinema": false,
        "titleAlt": "Поліна і таємниця кіностудії",
        "ratingAlt": "0+",
        "ratingDescriptionAlt": "",
        "synopsisAlt": "Україна, Франція, Бельгія",
        "shortSynopsisAlt": "Wild Tribe Films, Kinorob",
        "websiteUrl": "",
        "genreId": "0000000002",
        "eDICode": null,
        "twitterTag": "українська",
        "titleTranslations": [],
        "synopsisTranslations": [],
        "shortSynopsisTranslations": [],
        "ratingDescriptionTranslations": [],
        "customerRatingStatistics": {
         "ratingCount": 0,
         "averageScore": null
        },
        "customerRatingTrailerStatistics": {
         "ratingCount": 3,
         "ratingCountLiked": 0
        },
        "filmWebId": ""
       }
window.ArrOfFilms= [filmInfo, filmInfo1, filmInfo2];       